### PR TITLE
Support for react-immutable-proptypes (#14)

### PR DESCRIPTION
**Pull request by Raathigesh**
So I decided to give it a go on this today itself because I got another idea to hack during the weekend 😆 

I'm still going through James awesome babel plugin handbook and this is my first plugin so the immutable plugin is a shameless copy of the JSON to prop-types plugin. So let me know if you notice any issues and would be happy to correct them.

### CODE REVIEW

**Comment by ritz078** [comment]
Hi,

Thanks a lot for the your contribution. I have also added you as a contributor.

**Comment by Raathigesh** [comment]
That's awesome. Thank you!

**Comment by ritz078** [comment]
It's live now.

**Comment by Raathigesh** [comment]
That's fast! It's been fun working on this 😃

**Pull request merged**
